spring:
   datasource:
      primary:
         url: jdbc:mysql://127.0.0.1:3306/jeecf?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
         username: root
         password: 12345678
   redis: #redis配置
      host: 127.0.0.1
      port: 6379
redis:
   host: 127.0.0.1
   port: 6379
   maxTotal: 100
   maxIdle: 30
   maxWaitMillis: 6000
   testWhileIdle: true
   timeBetweenEvictionRunsMillis: 30000
   minEvictableIdleTimeMillis: 1800000
file:
   plugin:
      upload:
         path: /Users/jianyiming/jeecf/plugin/real
         tmp: 
            path: /Users/jianyiming/jeecf/plugin/tmp
      suffix: jar
   tmpl:
      download:
         prefix:
            path: /Users/jianyiming/jeecf/tmpl/download
      upload:
         path: /Users/jianyiming/jeecf/tmpl/real
         tmp:
            path: /Users/jianyiming/jeecf/tmpl/tmp
      suffix: zip
encrypt:
   key: 12345678     
